db:
  image: k0st/alpine-mariadb
#  volumes: 
#  - /data/mydb:/var/lib/mysql
  environment:
  - MYSQL_DATABASE=walla
  - MYSQL_USER=walla
  - MYSQL_PASSWORD=wallapass

web:
  image: test/wallabag
  environment:
  - DEBUG=1
  - SUBURI=/walla
  ports:
   - "10080:80"
  links:
   - db
